exports.promptList = [
    "Build a music website with artist pages, albums, and streaming features.",
    "Create a photography portfolio with galleries, client testimonials, and booking forms.",
    "Design a video streaming platform with channels, subscriptions, and playlists.",
    "Generate a recipe website with categories, ingredients, and cooking instructions.",
    "Build a podcast platform with episodes, show notes, and listener comments.",
    "Create a fashion blog with outfit ideas, trend reviews, and shopping links.",
    "Design a technology website with product reviews, news articles, and forums.",
    "Generate a sports platform with game schedules, player stats, and team profiles.",
    "Build a health website with medical advice, fitness tips, and appointment booking.",
    "Create a finance blog with investment guides, market updates, and calculators.",
    "Design a gaming website with game reviews, walkthroughs, and user forums.",
    "Generate a car website with vehicle listings, dealer info, and maintenance tips.",
    "Build a home decor site with interior design ideas, DIY projects, and shop links.",
    "Create a pet care website with pet profiles, adoption listings, and vet advice.",
    "Design a gardening blog with plant guides, landscaping tips, and product recommendations.",
    "Generate a beauty website with makeup tutorials, skincare routines, and product reviews.",
    "Build a book review site with reading lists, author interviews, and discussion groups.",
    "Create a lifestyle blog with travel diaries, wellness tips, and personal stories.",
    "Design a nature website with wildlife facts, conservation efforts, and eco-friendly products.",
    "Generate a history platform with historical events, biographies, and artifact showcases.",
    "Build a science website with research articles, experiments, and educational resources.",
    "Create a space exploration site with astronomy news, planet profiles, and stargazing guides.",
    "Design a food blog with recipes, restaurant reviews, and culinary traditions.",
    "Generate a movie website with film recommendations, actor profiles, and fan theories.",
    "Build a music blog with concert reviews, album releases, and artist interviews.",
    "Create a travel platform with itinerary planning, local guides, and travel tips.",
    "Design a sports blog with game highlights, player interviews, and fan polls.",
    "Generate a fashion website with style guides, runway trends, and designer spotlights.",
    "Build a tech blog with gadget reviews, software updates, and tech event coverage.",
    "Create a health platform with wellness challenges, nutrition tips, and mental health resources.",
    "Design a finance website with budgeting tools, investment strategies, and market analysis.",
    "Generate a gaming blog with game reviews, e-sports coverage, and gaming community features.",
    "Build a car platform with vehicle comparisons, auto news, and car enthusiast forums.",
    "Create a home improvement site with renovation ideas, DIY tutorials, and contractor listings.",
    "Design a pet blog with pet care tips, animal rescue stories, and pet product reviews.",
    "Generate a gardening website with plant care guides, garden layouts, and landscaping ideas.",
    "Build a beauty platform with makeup trends, skincare routines, and beauty influencer collaborations.",
    "Create a book website with reading recommendations, author spotlights, and literary events.",
    "Design a lifestyle blog with wellness advice, productivity tips, and personal development.",
    "Generate a nature platform with outdoor activities, wildlife photography, and environmental news.",
    "Build a history website with historical timelines, archival photos, and history quizzes.",
    "Create a science blog with scientific discoveries, research breakthroughs, and science experiments.",
    "Design a space exploration site with space missions, astronaut profiles, and space technology.",
    "Generate a food platform with cooking tutorials, food photography, and culinary travel guides.",
    "Build a movie website with movie reviews, film festivals, and cinema history.",
    "Create a music blog with music reviews, concert highlights, and music festival coverage.",
    "Design a travel website with travel guides, destination reviews, and travel photography.",
    "Generate a sports platform with sports news, game analysis, and sports betting tips.",
    "Build a fashion blog with fashion trends, style advice, and fashion industry news.",
    "Create a tech website with tech reviews, software tutorials, and tech industry updates.",
    "Design a health platform with health tips, medical advice, and wellness programs.",
    "Generate a finance blog with financial planning, investment advice, and money-saving tips.",
    "Build a gaming website with game reviews, gaming news, and game development updates and get data from a free open api.",
    "Create a car platform with car reviews, auto news, and car maintenance tips.",
    "Design a home decor site with interior design tips, home renovation ideas, and furniture guides.",
    "Generate a pet care website with pet health tips, pet grooming tutorials, and pet adoption listings.",
    "Build a gardening blog with gardening tips, plant care guides, and landscaping ideas.",
    "Create a beauty website with beauty tips, skincare routines, and makeup tutorials.",
    "Design a book review site with book recommendations, author interviews, and literary discussions.",
    "Generate a lifestyle blog with lifestyle tips, personal stories, and wellness advice.",
    "Build a nature website with nature photography, wildlife facts, and environmental conservation.",
    "Create a history platform with historical events, history articles, and history quizzes.",
    "Design a science website with science experiments, scientific research, and science news.",
    "Generate a space exploration site with space facts, astronomy news, and space technology.",
    "Build a food blog with food recipes, cooking tutorials, and restaurant reviews.",
    "Create a movie website with movie recommendations, film reviews, and movie trailers.",
    "Design a music platform with music reviews, music news, and music artist profiles.",
    "Generate a travel blog with travel stories, travel tips, and travel photography.",
    "Build a sports website with sports news, sports events, and sports highlights.",
    "Create a fashion platform with fashion trends, fashion news, and fashion designer profiles.",
    "Design a tech blog with tech reviews, tech news, and tech tutorials.",
    "Generate a health website with health tips, health news, and health resources.",
    "Build a finance website with financial tips, investment advice, and money management tools.",
    "Create a gaming platform with game reviews, gaming news, and game development updates and get data from a free open api.",
    "Design a car blog with car reviews, auto news, and car maintenance tips.",


  ];
  